two-new-card-achievement-section
E-Cell-SSTC/E-Cell-Website pull request #44
Opened 2021-11-18 14:29 UTC by Darshna-Shrivastava

2021-11-18 15:07 UTC, Darshna-Shrivastava commented on index.html
> +          </div>
New card has been added

2021-11-19 08:34 UTC, pixan198 requested changes
Hey @Darshna-Shrivastava 
Thanks for updating the details
In my opinion it'll be great if you add these cards at the beginning of the container as these are latest updates

2021-11-19 08:38 UTC, Sam-Ny reviewed
@Darshna-Shrivastava , Also it would be great if we can have one more card to add onto it, coz it is looking uneven . Ask @adivya-5 for more details.

2021-11-19 10:20 UTC, pixan198 approved these changes
LGTM ✅

2021-11-20 08:14 UTC, merged